server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: mcp-client
  #main:
   # web-application-type: none
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      embedding:
        options:
          model: text-embedding-v1
    mcp:
      client:
        toolcallback:
          enabled: true
        sse:
          connections:
            server1:
              # http://localhost:8080/sse/mcp
              url: http://localhost:8080
    memory:
      redis:
        host: 127.0.0.1
        port: 6379
        password: ""
        timeout: 2000
    elasticsearch:
      uris: http://127.0.0.1:9200
      username:
      password:
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: mall-vector
        similarity: cosine
        dimensions: 1536
  mandatory-file-encoding: UTF-8

# ????
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG

ai:
  user:
    input: ????????
