server:
  port: 8085

spring:
  application:
    name: mall-order-es-vector
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      embedding:
        options:
          model: text-embedding-v1
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: mall-vector
        similarity: cosine
        dimensions: 1536
    elasticsearch:
      uris: http://127.0.0.1:9200
      username:
      password:
