
spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: mall-order-cmp-server
        version: 0.0.1
        type: ASYNC  # Recommended for reactive applications
        # ?? sse ????????? /sse
        # ???????? ip:port/sse/mcp
        sse-endpoint: /sse
        sse-message-endpoint: /mcp
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
server:
  port: 8080